server:
  port: 8000



spring:
  application:
    name: api-gateway
  #链路追踪
  zipkin:
    base-url: http://127.0.0.1:9411/ #zipkin server地址
    discovery-client-enabled: false #让nacos把他当成URL 并不是服务名
  sleuth:
    sampler:
      probability: 1.0 #采样百分比
  cloud:
    #网关
    gateway:
      routes:                                 #路由数组[ 多个路由 请求满足什么条件转发到指定的微服务]
        - id : prodoct_route                  #当前路由的标识,要求唯一
          uri: lb://service-product           #lb指从nacos中获取微服务病遵循负载均衡->LoadBalancerClientFilter
          predicates:                         #断言,转发请求要满足的条件
            - Path=/product-serv/**
            #- Before=
            #- Method=
            #- Age=18,60                      #自定义断言18-60可以访问
          filters:                            #请求传递过程中对请求进行过滤
            - StripPrefix=1                   #在请求转发之前去掉一层路径 http://127.0.0.1:8000/product-serv/product/1->http://127.0.0.1:8000/product/1
            #- Log=true,false                 #自定义过滤器
        - id: order_route                     #当前路由的标识,要求唯一
          uri: lb://service-order           #lb指从nacos中获取微服务病遵循负载均衡->LoadBalancerClientFilter
          predicates:
            - Path=/order-serv/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true                       #让gateway发现nacos微服务列表
    #注册中心
    nacos:
      discovery:
        server-addr: http://nacos.chensi.site/
